// D12 - CodeAct via Hyperlight: the agent writes Python and executes it in a
// sandboxed micro-VM instead of chaining many separate tool calls.
//
// Two scenarios are demonstrated in sequence:
//   DEMO 1 - Pure interpreter. The provider exposes only `execute_code`.
//            The model answers quantitative questions by writing Python.
//   DEMO 2 - Provider-owned tools. `get_weather`, `convert_temperature` and
//            `book_trip` (approval-required) are registered on the provider:
//            the model reaches them with `call_tool(...)` from inside one
//            `execute_code` block, instead of N separate tool calls.
//
// A function-invocation middleware prints the Python code generated by the
// model so the audience can see what CodeAct actually does.

using System.ComponentModel;
using System.Diagnostics;
using HyperlightSandbox.Guest.Python;
using Maf.Demo.Shared;
using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Hyperlight;
using Microsoft.Extensions.AI;

const string ServiceName = "D12.CodeAct";

using TelemetryBundle telemetry = Telemetry.ConfigureConsole(ServiceName);
using var activitySource = new ActivitySource(ServiceName);
using var rootActivity = activitySource.StartActivity("INIT", ActivityKind.Client);

IChatClient chat = ChatClientFactory.Create(ServiceName);

// The guest module is bundled by the Hyperlight.HyperlightSandbox.Guest.Python
// package; this call resolves its path automatically.
string guestPath = PythonGuestModule.GetModulePath();

// ============================================================
// DEMO 1 - Pure interpreter (no host tools)
// ============================================================
Console.WriteLine();
Console.WriteLine(new string('=', 60));
Console.WriteLine("  DEMO 1: Pure code interpreter");
Console.WriteLine("  Scope: the agent answers by writing and running Python");
Console.WriteLine(new string('=', 60));
Console.WriteLine();

using (var codeActInterpreter = new HyperlightCodeActProvider(
    HyperlightCodeActProviderOptions.CreateForWasm(guestPath)))
{
    AIAgent interpreterAgent = new ChatClientAgent(chat, new ChatClientAgentOptions
    {
        Name = "trip-calculator",
        ChatOptions = new ChatOptions
        {
            Instructions =
                "Sei un assistente di viaggio. Per qualunque calcolo (distanze, tempi, " +
                "consumi) scrivi un breve programma Python e chiamalo con `execute_code` " +
                "invece di tirare a indovinare. Termina sempre il codice con print(...) " +
                "per restituire il risultato.",
        },
        AIContextProviders = [codeActInterpreter],
    })
    .AsBuilder()
    .Use(LogPythonCode)
    .Build()
    .WithOpenTelemetry(ServiceName);

    await Ask(interpreterAgent,
        "Calcola il tempo di percorrenza da Torino a Roma " +
        "(685 km) viaggiando a una media di 105 km/h, e quanti caffe' (1 ogni 90 min) " +
        "dovrei bere per non addormentarmi.");
}

Console.WriteLine();
Console.WriteLine("Premi un tasto per passare alla demo successiva...");
Console.ReadKey(true);

// ============================================================
// DEMO 2 - Provider-owned tools reachable from inside execute_code
// ============================================================
Console.WriteLine();
Console.WriteLine(new string('=', 60));
Console.WriteLine("  DEMO 2: Provider-owned tools (call_tool from sandbox)");
Console.WriteLine("  Scope: 3 tool ma una sola execute_code invece di N round-trip");
Console.WriteLine(new string('=', 60));
Console.WriteLine();

AIFunction getWeather = AIFunctionFactory.Create(
    ([Description("Nome citta")] string city) => city.ToLowerInvariant() switch
    {
        "torino" => "{\"temp_c\": 18, \"sky\": \"sereno\"}",
        "roma" => "{\"temp_c\": 26, \"sky\": \"sole\"}",
        "milano" => "{\"temp_c\": 21, \"sky\": \"nuvoloso\"}",
        _ => "{\"temp_c\": 20, \"sky\": \"sconosciuto\"}",
    },
    name: "get_weather",
    description: "Restituisce un JSON con temperatura in C e condizioni per la citta indicata.");

AIFunction convertTemperature = AIFunctionFactory.Create(
    ([Description("Temperatura in C")] double celsius) => celsius * 9.0 / 5.0 + 32.0,
    name: "convert_c_to_f",
    description: "Converte una temperatura da gradi Celsius a Fahrenheit.");

// Sensitive tool: wrapping in ApprovalRequiredAIFunction causes the WHOLE
// execute_code block to require user approval whenever it might be reached.
AIFunction bookTrip = new ApprovalRequiredAIFunction(
    AIFunctionFactory.Create(
        ([Description("Citta di partenza")] string from,
         [Description("Citta di arrivo")] string to,
         [Description("Data ISO YYYY-MM-DD")] string date) =>
            $"Prenotazione confermata: {from} -> {to} il {date}.",
        name: "book_trip",
        description: "Prenota un viaggio tra due citta. Operazione sensibile."));

var codeActOptions = HyperlightCodeActProviderOptions.CreateForWasm(guestPath);
codeActOptions.Tools = [getWeather, convertTemperature, bookTrip];

using (var codeActWithTools = new HyperlightCodeActProvider(codeActOptions))
{
    AIAgent travelAgent = new ChatClientAgent(chat, new ChatClientAgentOptions
    {
        Name = "travel-assistant",
        ChatOptions = new ChatOptions
        {
            Instructions =
                "Sei un assistente di viaggio. Preferisci orchestrare il lavoro in un " +
                "SINGOLO blocco execute_code chiamando i tool con `call_tool(\"name\", ...)` " +
                "invece di emettere tante tool call separate. Termina con print(...).",
        },
        AIContextProviders = [codeActWithTools],
    })
    .AsBuilder()
    .Use(LogPythonCode)
    .Build()
    .WithOpenTelemetry(ServiceName);

    // The model is expected to write ONE Python block that:
    //   1. calls get_weather for both cities
    //   2. converts the temperatures to Fahrenheit
    //   3. prints a summary
    await Ask(travelAgent,
        "Confronta meteo di Torino e Roma in Celsius e Fahrenheit, " +
        "e dimmi quale citta e' piu' calda.");

    // This one should pass through ApprovalRequiredAIFunction.
    Console.WriteLine();
    Console.WriteLine("(la prossima richiesta tocca book_trip -> serve approvazione)");
    await AskWithApproval(travelAgent,
        "Prenota il viaggio da Torino a Roma per il 2026-06-01.");
}

// --------- helpers ---------

static async Task Ask(AIAgent agent, string prompt)
{
    Console.WriteLine();
    Console.WriteLine(new string('-', 60));
    Console.WriteLine($"User: {prompt}");
    Console.WriteLine(new string('-', 60));
    AgentResponse response = await agent.RunAsync(prompt);
    Console.WriteLine();
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"Agent: {response.Text}");
    Console.ResetColor();
}

static async Task AskWithApproval(AIAgent agent, string prompt)
{
    Console.WriteLine();
    Console.WriteLine(new string('-', 60));
    Console.WriteLine($"User: {prompt}");
    Console.WriteLine(new string('-', 60));

    AgentSession session = await agent.CreateSessionAsync();
    AgentResponse response = await agent.RunAsync(prompt, session);

    // Handle approval requests for execute_code when a sensitive tool is reachable.
    while (true)
    {
        ToolApprovalRequestContent? approvalRequest = response.Messages
            .SelectMany(m => m.Contents)
            .OfType<ToolApprovalRequestContent>()
            .FirstOrDefault();

        if (approvalRequest is null) break;

        var call = (FunctionCallContent)approvalRequest.ToolCall;
        Console.ForegroundColor = ConsoleColor.Yellow;
        Console.WriteLine();
        Console.WriteLine($"[HITL] L'agente vuole eseguire: {call.Name}");
        Console.ResetColor();
        Console.Write("Approvi? (Y/n) ");
        bool approved = !string.Equals(Console.ReadLine()?.Trim(), "n", StringComparison.OrdinalIgnoreCase);

        ChatMessage decision = new(ChatRole.User, [approvalRequest.CreateResponse(approved)]);
        response = await agent.RunAsync([decision], session);
    }

    Console.WriteLine();
    Console.ForegroundColor = ConsoleColor.Green;
    Console.WriteLine($"Agent: {response.Text}");
    Console.ResetColor();
}

// Function-invocation middleware: prints the Python code submitted to execute_code
// and the stdout returned by the sandbox. This is what makes CodeAct visible live.
static async ValueTask<object?> LogPythonCode(
    AIAgent agent,
    FunctionInvocationContext context,
    Func<FunctionInvocationContext, CancellationToken, ValueTask<object?>> next,
    CancellationToken ct)
{
    if (context.Function.Name == "execute_code"
        && context.Arguments.TryGetValue("code", out object? codeObj)
        && codeObj is string code)
    {
        Console.ForegroundColor = ConsoleColor.DarkYellow;
        Console.WriteLine();
        Console.WriteLine(new string('=', 60));
        Console.WriteLine("[execute_code]");
        Console.WriteLine(new string('-', 60));
        Console.ResetColor();
        Console.WriteLine(code);
        Console.ForegroundColor = ConsoleColor.DarkYellow;
        Console.WriteLine(new string('=', 60));
        Console.ResetColor();
    }
    else
    {
        Console.ForegroundColor = ConsoleColor.Magenta;
        Console.WriteLine($"[tool] {context.Function.Name}({string.Join(", ", context.Arguments.Select(kv => $"{kv.Key}={kv.Value}"))})");
        Console.ResetColor();
    }

    object? result = await next(context, ct);

    if (context.Function.Name == "execute_code")
    {
        Console.ForegroundColor = ConsoleColor.DarkGreen;
        Console.WriteLine("[stdout]");
        Console.WriteLine(result);
        Console.ResetColor();
    }

    return result;
}
